//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Client
    {
        public string cnp { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public Nullable<int> penaltyPoints { get; set; }
        public Nullable<System.DateTime> ableToBorrow { get; set; }
        public Nullable<int> nrOfMovies { get; set; }
    }
}
