//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Movie
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public string actors { get; set; }
        public string clientCNP { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> nrOfRatings { get; set; }
    }
}
