//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Report
    {
        public int ID { get; set; }
        public string client { get; set; }
        public int borrowedNow { get; set; }
        public string movie { get; set; }
        public int movieID { get; set; }
        public string clientCnp { get; set; }
    }
}
