//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Review
    {
        public int id { get; set; }
        public int movieID { get; set; }
        public string review1 { get; set; }
    }
}
